/*
 ******************************************************************************
 File:     main.c
 Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2019-02-27

 The MIT License (MIT)
 Copyright (c) 2019 STMicroelectronics

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 ******************************************************************************
 */

#include "mina_shield_mbed.h"
#include "mbed_shield_lcd.h"
#include "nucleo_usart.h"


volatile uint32_t ticks = 0;
void SysTick_Handler(void) {
	ticks++;
}

void DrawBackground(uint32_t rezim) {

	MBED_LCD_WriteCharXY('R', 0, 0);
	MBED_LCD_WriteCharXY('G', 5, 0);
	MBED_LCD_WriteCharXY('B', 10, 0);

	MBED_LCD_DrawRect(18, 2, 12, 27, true); // R

	MBED_LCD_DrawRect(58, 2, 12, 27, true); // G

	MBED_LCD_DrawRect(98, 2, 12, 27, true); // B

	if (rezim == 0) {

		MBED_LCD_DrawRect(16, 0, 16, 31, true);
		MBED_LCD_DrawRect(56, 0, 16, 31, false);
		MBED_LCD_DrawRect(96, 0, 16, 31, false);

	} else if (rezim == 1) {

		MBED_LCD_DrawRect(16, 0, 16, 31, false);
		MBED_LCD_DrawRect(56, 0, 16, 31, true);
		MBED_LCD_DrawRect(96, 0, 16, 31, false);

	} else if (rezim == 2) {

		MBED_LCD_DrawRect(16, 0, 16, 31, false);
		MBED_LCD_DrawRect(56, 0, 16, 31, false);
		MBED_LCD_DrawRect(96, 0, 16, 31, true);

	} else {

	}

	MBED_LCD_VideoRam2LCD();

}

void DrawFront(uint32_t r, uint32_t g, uint32_t b) {

	r = (r * 26) / 255;
	g = (g * 26) / 255;
	b = (b * 26) / 255;

	MBED_LCD_FillRect(19, 3, 11, 26, false); // R

	MBED_LCD_FillRect(59, 3, 11, 26, false); // G

	MBED_LCD_FillRect(99, 3, 11, 26, false); // B

	/////////////////////////////////////////////////////

	MBED_LCD_FillRect(19, 3 + (26 - r), 11, r, true); // R (X,Y,W,H)

	MBED_LCD_FillRect(59, 3 + (26 - g), 11, g, true); // G

	MBED_LCD_FillRect(99, 3 + (26 - b), 11, b, true); // B

	/////////////////////////////////////////////////////

	MBED_LCD_VideoRam2LCD();

}

void DeleateBackground(void) {

	MBED_LCD_FillRect(0, 0, 128, 32, false);

	MBED_LCD_VideoRam2LCD();

}

void SetPWM(uint8_t r, uint8_t g, uint8_t b) {
	TIM3->CCR2 = TIM3->ARR - g;
	TIM3->CCR1 = TIM3->ARR - r;
	TIM1->CCR2 = TIM1->ARR - b;
	DrawFront(r, g, b);
}

int main(void) {

	////////// VAR ///////////////////////////////////////////////////////////////////////////////////////////////////////////////

	uint8_t rezim = 0;

	uint8_t r = 0;
	uint8_t g = 0;
	uint8_t b = 0;

	uint32_t timeConstant = 1000;

	////////// VAR ///// CON /////////////////////////////////////////////////////////////////////////////////////////////////////
	SystemCoreClockUpdate();

	SysTick_Config(SystemCoreClock / 1000);

	Usart2Initialization(38400);

	GPIOConfigurePin(JOY_LEFT, ioPortInputFloat);

	GPIOConfigurePin(JOY_RIGHT, ioPortInputFloat);

	GPIOConfigurePin(JOY_UP, ioPortInputFloat);

	GPIOConfigurePin(JOY_DOWN, ioPortInputFloat);

	GPIOConfigurePin(JOY_CENTER, ioPortInputFloat);

	////////// CON ///// LCD /////////////////////////////////////////////////////////////////////////////////////////////////////
	if (!MBED_LCD_init()) {
		while (1)
			;
	}

	MBED_LCD_InitVideoRam(0x00);    // fill content with 0 = clear memory buffer

	////////// LCD ///// PWM /////////////////////////////////////////////////////////////////////////////////////////////////////

	uint32_t apb2 = SystemCoreClock; //TODO dopln podle RCC (16MHz)

	if (!(RCC->APB2ENR & RCC_APB2ENR_TIM1EN)) // v DataSheet str15 je vidìt že TIM1 je na sbìrnici APB2
	{
		RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;
		RCC->APB2RSTR |= RCC_APB2RSTR_TIM1RST;
		RCC->APB2RSTR &= ~RCC_APB2RSTR_TIM1RST;
	} // nastaven TIM1

	TIM1->CR1 = 0 | TIM_CR1_ARPE; // up counter(poèítá nahoru)
	TIM1->CR2 = 0;
	TIM1->PSC = apb2 / 1E6 - 1; // (1us) => MHz
	TIM1->ARR = 256 - 1; // (1000-1 => pøeteèe každou 1ms => kHz)
	TIM1->CR1 = TIM_CR1_CEN;

	TIM1->BDTR |= TIM_BDTR_MOE; //nutno nastavit, na jedna (povoluje OC výstupù), urèeno k jednoduchému odpojení motorových budièù

	GPIOConfigurePin(RGBLED_BLUE, ioPortAlternatrPushPull);
	GPIOConfigureAlternativFunction(RGBLED_BLUE, 1); // AF01 odpovida TIM1_CH2N => datasheet

	TIM1->CCMR1 &= ~TIM_CCMR1_OC2M; // Pozor!! nutno OC2M protože potøebueme druhý kanál!!!!
	TIM1->CCMR1 |= TIM_CCMR1_OC2M_2 | TIM_CCMR1_OC2M_1; // _2 a _1 jako prvni a druhy bit, 110 – PWM 1
	TIM1->CCER |= TIM_CCER_CC2E; // kánál 2 enable (musí být jenom E!!!)
	TIM1->CCR2 = TIM1->ARR / 2; // polovina TIM3 ARR, takže støída 50%

	// RM str 355

	if (!(RCC->APB1ENR & RCC_APB1ENR_TIM3EN)) // v DataSheet str15 je vidìt že TIM1 je na sbìrnici APB2
	{
		RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
		RCC->APB1RSTR |= RCC_APB1RSTR_TIM3RST;
		RCC->APB1RSTR &= ~RCC_APB1RSTR_TIM3RST;
	} // nastaven TIM3

	TIM3->CR1 = 0 | TIM_CR1_ARPE; // up counter(poèítá nahoru)
	TIM3->CR2 = 0;
	TIM3->PSC = apb2 / 1E6 - 1; // (1us) => MHz
	TIM3->ARR = 256 - 1; // (pøeteèe každou 256us)
	TIM3->CR1 = TIM_CR1_CEN;

	GPIOConfigurePin(RGBLED_RED, ioPortAlternatrPushPull);
	GPIOConfigureAlternativFunction(RGBLED_RED, 2); // AF02 odpovida TIM3_CH1N => datasheet

	TIM3->CCMR1 &= ~TIM_CCMR1_OC1M; // Pozor!! nutno OC1M protože potøebueme první kanál!!!!
	TIM3->CCMR1 |= TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1; // _2 a _1 jako prvni a druhy bit, 110 – PWM 1
	TIM3->CCER |= TIM_CCER_CC1E; // kánál 1 enable (musí být jenom E!!!)
	TIM3->CCR1 = TIM3->ARR / 2; // polovina TIM3 ARR, takže støída 50%

	GPIOConfigurePin(RGBLED_GREEN, ioPortAlternatrPushPull);
	GPIOConfigureAlternativFunction(RGBLED_GREEN, 2); // AF02 odpovida TIM3_CH2N => datasheet

	TIM3->CCMR1 &= ~TIM_CCMR1_OC2M; // Pozor!! nutno OC2M protože potøebueme druhý kanál!!!!
	TIM3->CCMR1 |= TIM_CCMR1_OC2M_2 | TIM_CCMR1_OC2M_1; // _2 a _1 jako prvni a druhy bit, 110 – PWM 1
	TIM3->CCER |= TIM_CCER_CC2E; // kánál 1 enable (musí být jenom E!!!)
	TIM3->CCR2 = TIM3->ARR / 2; // polovina TIM3 ARR, takže støída 50%

	// RM str 355
	////////// PWM ///// SPE /////////////////////////////////////////////////////////////////////////////////////////////////////

	if (!(RCC->APB1ENR & RCC_APB1ENR_TIM2EN)) // v DataSheet str15 je vidìt že TIM2 je na sbìrnici APB1
		{
				RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
				RCC->APB1RSTR |= RCC_APB1RSTR_TIM2RST;
				RCC->APB1RSTR &= ~RCC_APB1RSTR_TIM2RST;
		} // nastaven TIM2

			TIM2->CR1 = 0 | TIM_CR1_ARPE; // nula aby --> up counter(poèítá nahoru) a ten ARPE je aby to nevznechávalo jeden takt myslím
			TIM2->CR2 = 0;
			TIM2->PSC = apb2 / 1E6 - 1; // (1us) => MHz
			TIM2->ARR = 1000-1; // (1000-1 => pøeteèe každou 1ms => kHz)
			TIM2->CR1 = TIM_CR1_CEN;


			GPIOConfigurePin(SPEAKER, ioPortAlternatrPushPull);
			GPIOConfigureAlternativFunction(SPEAKER, 1); // AF01 odpovida TIM2_CH3N => datasheet


			TIM2->CCMR2 &= ~TIM_CCMR2_OC3M; // Pozor!! nutno OC2M protože potøebueme druhý kanál!!!!
			TIM2->CCMR2 |= TIM_CCMR2_OC3M_2 | TIM_CCMR2_OC3M_1; // _2 a _1 jako prvni a druhy bit, 110 – PWM 1
			TIM2->CCER |= TIM_CCER_CC3E; // kánál 3 enable (musí být jenom E!!!)
			TIM2->CCR3 = TIM2->ARR+1;

		    // RM str 355

	////////// SPE ///////////////////////////////////////////////////////////////////////////////////////////////////////////////


	DeleateBackground();
	DrawBackground(rezim);
	SetPWM(r, g, b);

	while (1) {

		if (ticks >= timeConstant) {

			timeConstant = ticks + 1000;
			printf("\nBarva: 0x%x%x%x",r,g,b);
			printf("\nStav:\n R: %d%%\n G: %d%%\n B: %d%%\n\n\n",(r*100/255),(g*100/255),(b*100/255));

		}

		if (GPIORead(JOY_LEFT)) {
			rezim--;
			if (rezim == 255) {
				rezim = 2;
			}
			while (GPIORead(JOY_LEFT))
				;
			DrawBackground(rezim);
		}
		if (GPIORead(JOY_RIGHT)) {
			rezim++;
			if (rezim == 3) {
				rezim = 0;
			}
			while (GPIORead(JOY_RIGHT))
				;
			DrawBackground(rezim);
		}
		while (GPIORead(JOY_UP)) {
			if (rezim == 0) {
				if (r != 255) {
					r++;
				}
			} else if (rezim == 1) {
				if (g != 255) {
					g++;
				}
			} else if (rezim == 2) {
				if (b != 255) {
					b++;
				}
			}
			SetPWM(r, g, b);

		}
		while (GPIORead(JOY_DOWN)) {
			if (rezim == 0) {
				if (r != 0) {
					r--;
				}
			} else if (rezim == 1) {
				if (g != 0) {
					g--;
				}
			} else if (rezim == 2) {
				if (b != 0) {
					b--;
				}
			}

			SetPWM(r, g, b);

		}
		if (GPIORead(JOY_CENTER)) {

				r = 0;
				g = 0;
				b = 0;

			SetPWM(r, g, b);

			while (GPIORead(JOY_CENTER))
			{
				TIM2->CCR3 = TIM2->ARR/2;
			}

			TIM2->CCR3 = TIM2->ARR +1;
				;
		}

		if (IsUsart2Recived()) {
			char x = Usart2Recived();

			if((r<5)&&(!(r%5)==0))
			{
				r=0;
			}
			else
			{
			while(!(r%5)==0)
			{
				r--;
			}
			}
			if((g<5)&&(!(g%5)==0))
			{
				g=0;
			}
			else
			{
			while(!(g%5)==0)
			{
				g--;
			}
			}
			if((b<5)&&(!(b%5)==0))
			{
				b=0;
			}
			else
			{
			while(!(b%5)==0)
			{
				b--;
			}
			}

			if (x == 'a') {
				rezim--;
				if (rezim == 255) {
					rezim = 2;
				}
				DrawBackground(rezim);
			}
			if (x == 'd') {
				rezim++;
				if (rezim == 3) {
					rezim = 0;
				}
				DrawBackground(rezim);
			}
			if (x == 'w') {
				if (rezim == 0) {
					if (r != 255) {
						r+=5;
					}
				} else if (rezim == 1) {
					if (g != 255) {
						g+=5;
					}
				} else if (rezim == 2) {
					if (b != 255) {
						b+=5;
					}
				}
				SetPWM(r, g, b);

			}
			if (x == 's') {
				if (rezim == 0) {
					if (r != 0) {
						r-=5;
					}
				} else if (rezim == 1) {
					if (g != 0) {
						g-=5;
					}
				} else if (rezim == 2) {
					if (b != 0) {
						b-=5;
					}
				}

				SetPWM(r, g, b);


			}
				if (x == 'r')
				{
					r = 0;
					g = 0;
					b = 0;

					SetPWM(r, g, b);

					TIM2->CCR3 = TIM2->ARR/2;

					for(int i =0;i<100000;i++);

					TIM2->CCR3 = TIM2->ARR +1;
								;
	    			}

		}

	}
}
