/*
 ******************************************************************************
 File:     main.c
 Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2019-04-18

 The MIT License (MIT)
 Copyright (c) 2019 STMicroelectronics

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 ******************************************************************************
 */

/* Includes */
#include "stm32f4xx.h"
#include "nucleo_i2c.h"
#include "mpp_shield.h"
#include "system_stm32f4xx.h"
#include "nucleo_usart.h"


#define MMA7660SENS 21.33
#define MMA7660ADR 0x98 // 1001100 0 (1)

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
 **===========================================================================
 **
 **  Abstract: main program
 **
 **===========================================================================
 */
volatile uint32_t ticks = 0; // promìná která symbolizuje dobìhnutí hodin
// "volatile" znamená že kompilátor tuto promìnou nebude optimalizovat, to je tøeba, protože by jinak mohl kompilátor dojít k chybným závìrùm o fknci nìkterých programových konstrukcí a nesprávnì program optimalizovat

void SysTick_Handler(void) // tato funkce musí mít pøesnì takovýto název, jinak se pøi pøerušení volá defalutnì nastavená
{
	ticks++;
}

float Acc2Float(uint8_t accVal) {
	int val = 0;
	if (accVal & 0x20) // nevyssi bit 6-bitove ?
		val = -(32 - (accVal & 0x1f)); // zaporne - vezmi 5bitu a odecti od 32
	else
		val = accVal & 0x1f; // jen spodnich 5 bitu
	return val / MMA7660SENS; // deleni je floatove - konstanta je float
}

int main(void) {

	uint8_t x;

	uint8_t y;

	uint8_t z;

	uint32_t timeConstant = 100;

	SystemCoreClockUpdate();

	SysTick_Config(SystemCoreClock / 1000); // nastavení èasovaèe pro pøerušení

	Usart2Initialization(38400);

    puts("\nStart App\n");

	InitI2C1(i2cSpeed100k);

	I2C1_WriteByte(MMA7660ADR, 7, 1); // registr 7, hodnota 0000 0001 = MODE

	while (1) {
		if (ticks >= timeConstant) // casovani vysilani
				{
			timeConstant = ticks + 100;
			x = I2C1_ReadByte(MMA7660ADR, 0); // XOUT
            y = I2C1_ReadByte(MMA7660ADR,1);
            z = I2C1_ReadByte(MMA7660ADR,2);


			//printf("X=%02d, Y=%02d, Z=%02d\r\n Zrychleni osy x: %f\r\n",x,y,z,Acc2Float(x));
			printf("1;%d;%d;%d\r\n",x,y,z);
		}
	}
}

