/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2019-03-13

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm_core.h"
#include "mpp_shield.h"
#include "system_stm32f4xx.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
	volatile uint32_t ticks = 0;

	void SysTick_Handler(void)
	{
	ticks++;
	}

int Blik(uint32_t timeConstant, bool on, GPIO_TypeDef *gpio, uint32_t bitNum, uint32_t t )
{
	  if(on)
	  {
		if (ticks >= timeConstant)
		{
		GPIOToggle(gpio,bitNum);
		timeConstant = ticks + t;
		return timeConstant;
		}
	  }
	  return timeConstant;
}

bool Tap (bool on, GPIO_TypeDef *gpioled, uint32_t bitNumled, GPIO_TypeDef *gpiobutton, uint32_t bitNumbutton)
{

	  if(!GPIORead(gpiobutton,bitNumbutton))
	  {
		  if(on)
	      {

		  GPIOWrite(gpioled,bitNumled,false);
		  while(!GPIORead(gpiobutton,bitNumbutton));
		  return false;
	      }
		  else
		  {
			  while(!GPIORead(gpiobutton,bitNumbutton));
			  return true;
		  }
	  }
	  return on;

}


	int main(void)
	{

	uint32_t timeConstantBLUE = 50;
	uint32_t timeConstantGREEN = 75;
	uint32_t timeConstantRED = 100;
	uint32_t timeConstant0 = 10;
	uint32_t timeConstant1 = 20;
	uint32_t timeConstant2 = 30;
	uint32_t timeConstant3 = 50;
	uint32_t timeConstant4 = 70;
	uint32_t timeConstant5 = 110;
	uint32_t timeConstant6 = 130;
	uint32_t timeConstant7 = 170;

	SystemCoreClockUpdate();

	SysTick_Config(SystemCoreClock/1000);



	    GPIOConfigurePin(BUTTON_BLUE,ioPortInputFloat);
		GPIOConfigurePin(BUTTON_LEFT,ioPortInputFloat);
		GPIOConfigurePin(BUTTON_RIGHT,ioPortInputFloat);

		GPIOConfigurePin(RGBLED_BLUE,ioPortOutputPushPull);
		GPIOConfigurePin(RGBLED_GREEN,ioPortOutputPushPull);
		GPIOConfigurePin(RGBLED_RED,ioPortOutputPushPull);

		Inicializace8LED();

       bool onBLUE = true;
       bool onGREEN = true;
       bool onRED = true;


  while (1)
  {
	  timeConstantBLUE = Blik(timeConstantBLUE, onBLUE, RGBLED_BLUE,50);
	  timeConstantGREEN = Blik(timeConstantGREEN, onGREEN, RGBLED_GREEN,75);
	  timeConstantRED = Blik(timeConstantRED, onRED, RGBLED_RED,100);

	  onBLUE = Tap(onBLUE,RGBLED_BLUE,BUTTON_BLUE);
	  onGREEN = Tap(onGREEN,RGBLED_GREEN,BUTTON_LEFT);
	  onRED = Tap(onRED,RGBLED_RED,BUTTON_RIGHT);


	  timeConstant0 = Blik(timeConstant0, true, GPIOC,0,100);
	  timeConstant1 = Blik(timeConstant1, true, GPIOC,1,200);
	  timeConstant2 = Blik(timeConstant2, true, GPIOC,2, 300);
	  timeConstant3 = Blik(timeConstant3, true, GPIOC,3, 500);
	  timeConstant4 = Blik(timeConstant4, true, GPIOC,4, 700);
	  timeConstant5 = Blik(timeConstant5, true, GPIOC,5,1100);
	  timeConstant6 = Blik(timeConstant6, true, GPIOC,6,1300);
	  timeConstant7 = Blik(timeConstant7,true, GPIOC,7,1700);

  }
}
