/*
 * pin_defines.h
 *
 *  Created on: 16. 4. 2017
 *      Author: weiss_000
 */

#ifndef COMMON_PIN_DEFINES_H_
#define COMMON_PIN_DEFINES_H_

#define NUCLEO_A0   GPIOA,0
#define NUCLEO_A1   GPIOA,1
#define NUCLEO_A2   GPIOA,4
#define NUCLEO_A3   GPIOB,0
#define NUCLEO_A4   GPIOC,1
#define NUCLEO_A5   GPIOC,0

#define NUCLEO_D0   GPIOA,3
#define NUCLEO_D1   GPIOA,2
#define NUCLEO_D2   GPIOA,10
#define NUCLEO_D3   GPIOB,3
#define NUCLEO_D4   GPIOB,5
#define NUCLEO_D5   GPIOB,4
#define NUCLEO_D6   GPIOB,10
#define NUCLEO_D7   GPIOA,8

#define NUCLEO_D8   GPIOA,9
#define NUCLEO_D9   GPIOC,7
#define NUCLEO_D10  GPIOB,6
#define NUCLEO_D11  GPIOA,7
#define NUCLEO_D12  GPIOA,6
#define NUCLEO_D13  GPIOA,5

#define NUCLEO_D14  GPIOB,9
#define NUCLEO_D15  GPIOB,8

// ****************************

#define SHIELD_KL46_CLICK1_AN     NUCLEO_A0
#define SHIELD_KL46_CLICK1_RST    NUCLEO_A3
#define SHIELD_KL46_CLICK1_CS     NUCLEO_D10
#define SHIELD_KL46_CLICK1_SCK    NUCLEO_D13
#define SHIELD_KL46_CLICK1_MISO   NUCLEO_D12
#define SHIELD_KL46_CLICK1_MOSI   NUCLEO_D11

#define SHIELD_KL46_CLICK1_PWM    NUCLEO_D6
#define SHIELD_KL46_CLICK1_INT    NUCLEO_D2
#define SHIELD_KL46_CLICK1_RX     NUCLEO_D0
#define SHIELD_KL46_CLICK1_TX     NUCLEO_D1
#define SHIELD_KL46_CLICK1_SCL    NUCLEO_D15
#define SHIELD_KL46_CLICK1_SDA    NUCLEO_D14

#define SHIELD_KL46_CLICK2_AN     NUCLEO_A1
#define SHIELD_KL46_CLICK2_RST    NUCLEO_A2
#define SHIELD_KL46_CLICK2_CS     NUCLEO_D9
#define SHIELD_KL46_CLICK2_SCK    NUCLEO_D13
#define SHIELD_KL46_CLICK2_MISO   NUCLEO_D12
#define SHIELD_KL46_CLICK2_MOSI   NUCLEO_D11

#define SHIELD_KL46_CLICK2_PWM    NUCLEO_D5
#define SHIELD_KL46_CLICK2_INT    NUCLEO_D3
#define SHIELD_KL46_CLICK2_RX     NUCLEO_D0
#define SHIELD_KL46_CLICK2_TX     NUCLEO_D1
#define SHIELD_KL46_CLICK2_SCL    NUCLEO_A5
#define SHIELD_KL46_CLICK2_SDA    NUCLEO_A4

#endif /* COMMON_PIN_DEFINES_H_ */
