/*
 ******************************************************************************
 File:     main.c
 Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2019-03-06

 The MIT License (MIT)
 Copyright (c) 2019 STMicroelectronics

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 ******************************************************************************
 */

/* Includes */
#include "mpp_shield.h"
#include "system_stm32f4xx.h"
#include "nucleo_usart.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

void VypisPamet(unsigned char *UkazatelNaPamet) {

	printf("\r\nStart \r\n");
	for (int j = 0; j < 8; j++) {
		for (int i = 0; i < 8; i++) {
			printf("{%x} ", UkazatelNaPamet[i+(j*8)]);
		}
		printf("\r\n ");
	}
	printf("End\r\n ");
}

int main(void) {

	GPIOConfigurePin(BUZZER, ioPortOutputPushPull);
	GPIOConfigurePin(BUTTON_LEFT, ioPortInputFloat);

	Usart2Initialization(38400);

	puts("\nStart App\n");

	while (1) {


		unsigned char* pole;

		if (NULL == (pole = (unsigned char*)malloc(64))) { //allokuj pamet velikosti VELIKOST jako charový ukazatel.. protoze malloc vraci void.. od adresy "adresa"
			printf("Neni pamet\n");
			return -1;
		}

		VypisPamet(pole);

	    while(GPIORead(BUTTON_LEFT))
		{
		}

	}

}

