/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2019-03-03

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "mpp_shield.h"
#include "stm_core.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{


  /**
  *  IMPORTANT NOTE!
  *  The symbol VECT_TAB_SRAM needs to be defined when building the project
  *  if code has been located to RAM and interrupts are used. 
  *  Otherwise the interrupt table located in flash will be used.
  *  See also the <system_*.c> file and how the SystemInit() function updates 
  *  SCB->VTOR register.  
  *  E.g.  SCB->VTOR = 0x20000000;  
  */

  /* TODO - Add your application code here */

for(int i = 0;i<8;i++)
{
	GPIOConfigurePin(GPIOC,i,ioPortOutputPushPull);
}

	GPIOConfigurePin(GPIOA,8,ioPortOutputPushPull); // LE pøepisuje obsah posuvného registru do paralelního registru
	GPIOWrite(GPIOA,8,false); // klidový stav
	GPIOConfigurePin(GPIOA,9,ioPortOutputPushPull); // ~OE øízení výstupních budièù LED (aktivní v nule)
	GPIOWrite(GPIOA,9,false); // každá zmìna se hned promítne
	GPIOConfigurePin(GPIOA,5,ioPortOutputPushPull); // CLK hodiny
	GPIOWrite(GPIOA,5,false); // Hodiny do nuly
	GPIOConfigurePin(GPIOA,7,ioPortOutputPushPull); // SDI serial data input

	uint8_t i = 0;

  /* Infinite loop */
  while (1)
  {

		    Write8LED(0xff>>(7-i));
			WriteSPILED(0xff<<(7-i));

    i++;
	Sleep(500000);
	if(i==8)
	{
		i=0;
	}

  }
}
