/*
 ******************************************************************************
 File:     main.c
 Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2019-03-15

 The MIT License (MIT)
 Copyright (c) 2019 STMicroelectronics

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 ******************************************************************************
 */

/* Includes */
#include "stm_core.h"
#include "mpp_shield.h"
#include "system_stm32f4xx.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
 **===========================================================================
 **
 **  Abstract: main program
 **
 **===========================================================================
 */

int main(void) {

	uint32_t apb1 = SystemCoreClock; //TODO dopln podle RCC

	if (!(RCC->APB1ENR & RCC_APB1ENR_TIM3EN)) {
		RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
		RCC->APB1RSTR |= RCC_APB1RSTR_TIM3RST;
		RCC->APB1RSTR &= ~RCC_APB1RSTR_TIM3RST;
	}

	TIM3->CR1 = 0 | TIM_CR1_ARPE; //Dir = 0 => inkrementace... bufferovany (synchroni s pøeteèením) zapis do ARR
	TIM3->CR2 = 0;

	TIM3->PSC = apb1 / 1E6 - 1; // 1MHz (1us)
	TIM3->ARR = 1000 - 1; // 1kHz(1ms)
	TIM3->CR1 = TIM_CR1_CEN;

	GPIOConfigurePin(BUZZER, ioPortAlternatrPushPull);

	GPIOConfigureAlternativFunction(BUZZER, 2); // AF02 = TIM3_CH3 (tabulka 9. v DS)

	TIM3->CCMR2 &= ~TIM_CCMR2_OC3M; // vynulování tøí bitù urèujících mode
	TIM3->CCMR2 |= TIM_CCMR2_OC3M_2 | TIM_CCMR2_OC3M_1; // nastavení kombinace 110 (PWM mode neinvertovaný) aktivní úroveò pro CCRx < CNT
	TIM3->CCER |= TIM_CCER_CC3E; // output enable
	TIM3->CCR3 = TIM3->ARR / 2; // støída na polovinu poèítání (= 50%)

	while (1) {

	}
}
