/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2019-03-15

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm_core.h"
#include "mpp_shield.h"
#include "system_stm32f4xx.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/

   volatile bool tim3irq = false;

   void TIM3_IRQHandler(void) // obsluha preruseni od TIM3
   {
    static int cnt = 0; // lokalni ale staticka !!!
    TIM3->SR &= ~TIM_SR_UIF; // shodit priznak !!
    GPIOToggle(GPIOB, 0); // pipak
    cnt++;
     if (cnt >= 1000) // pocitej kazde 100x volani
     {
      cnt = 0;
      tim3irq = true;
     }
    }

   int main(void)
	{

	GPIOConfigurePin(RGBLED_BLUE,ioPortOutputPushPull);
	GPIOConfigurePin(BUZZER,ioPortOutputPushPull);

	if (!(RCC->APB1ENR & RCC_APB1ENR_TIM3EN))
	{
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
	RCC->APB1RSTR |= RCC_APB1RSTR_TIM3RST;
	RCC->APB1RSTR &= ~RCC_APB1RSTR_TIM3RST;
	}

	TIM3->CR1 = TIM_CR1_DIR; // DIR = 1 = dekrementace
	TIM3->CR2 = 0; //prostì jen reset
	TIM3->PSC = SystemCoreClock / 1000000 - 1; // Pro sbìrnici APB je èas nedìlený (možno zjistit pøi Debug, RCC (blok který se stará o distribuci hodinových signálù) CFGR(registr nastavující hodiny) PPRE1 (tøi bity v registru které nastavují dìlliè hodin pro sbìrniici APB1) a pøi pohledu na tyhle bity zjistime že jsou všechny log. 0 tudíš hodiny jsou nedìlené) u nás je clock právì systemCoreClock, takže 16MHz... my ho ještì podìlime 10^6 protože chceme mikrosekunu
	TIM3->ARR = 999; // z PSC nám leze 1 mikrosekunda, já chci pøeteèení každou milisekundu, takže (1000 - 1)

	TIM3->DIER = TIM_DIER_UIE; // Nastavení generování pøerušení ven, smìr do jádra (jednièka)
	NVIC_EnableIRQ(TIM3_IRQn); // povolení správce zaøízení(pøerušovací kontroler), //IGQje typ pøerušení

	TIM3->CR1 |= TIM_CR1_CEN; // enable

	while (1)
	{

	if (tim3irq)
		{
		tim3irq = false;
		GPIOToggle(RGBLED_BLUE);
		}
	}
}
