/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2019-02-27

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/


#include "mina_shield_mbed.h"

int main(void)
{

	// PWM: ARR jsou výška schodù, CCRx je kdy se pulz v dané periodì "vypne", pokud je CCRx v pulce schodù, dává 50%, pokud víc, støídá bude vìtší

	SystemCoreClockUpdate();

	SysTick_Config(SystemCoreClock / 1000);

	uint32_t apb1 = SystemCoreClock; //TODO dopln podle RCC (16MHz)

	if (!(RCC->APB1ENR & RCC_APB1ENR_TIM2EN)) // v DataSheet str15 je vidìt že TIM2 je na sbìrnici APB1
	{
			RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
			RCC->APB1RSTR |= RCC_APB1RSTR_TIM2RST;
			RCC->APB1RSTR &= ~RCC_APB1RSTR_TIM2RST;
	} // nastaven TIM2

		TIM2->CR1 = 0 | TIM_CR1_ARPE; // nula aby --> up counter(poèítá nahoru) a ten ARPE je aby to nevznechávalo jeden takt myslím
		TIM2->CR2 = 0;
		TIM2->PSC = apb1 / 1E6 - 1; // (1us) => MHz
		TIM2->ARR = 1000-1; // (1000-1 => pøeteèe každou 1ms => kHz)
		TIM2->CR1 = TIM_CR1_CEN;


		GPIOConfigurePin(SPEAKER, ioPortAlternatrPushPull);
		GPIOConfigureAlternativFunction(SPEAKER, 1); // AF01 odpovida TIM2_CH3N => datasheet


		TIM2->CCMR2 &= ~TIM_CCMR2_OC2M; // Pozor!! nutno OC2M protože potøebueme druhý kanál!!!!
		TIM2->CCMR2 |= TIM_CCMR2_OC2M_2 | TIM_CCMR2_OC3M_1; // _2 a _1 jako prvni a druhy bit, 110 – PWM 1
		TIM2->CCER |= TIM_CCER_CC2E; // kánál 2 enable (musí být jenom E!!!)
		TIM2->CCR3 = TIM2->ARR+1;

	    // RM str 355

		GPIOConfigurePin(JOY_CENTER,ioPortInputFloat);
		GPIOConfigurePin(RGBLED_BLUE,ioPortOutputPushPull);

			while (1)
			{

				if(!GPIORead(JOY_CENTER))
				{
					GPIOToggle(RGBLED_BLUE);
					if(!GPIORead(RGBLED_BLUE))
					{
					TIM2->CCR3 = TIM2->ARR/2;
					}
					else
					{
						TIM2->CCR3 = TIM2->ARR+1;
					}


				while(!GPIORead(JOY_CENTER));
				}


		}
	}
