/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2019-03-06

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm_core.h"
#include "mpp_shield.h"
#include "system_stm32f4xx.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */


int main(void)
{

SystemCoreClockUpdate(); // pøepoèítá hodnotu promìnné SystemCoreClock podle aktuálního nastavení dìlièek hodinového signálu

SysTick->LOAD = SystemCoreClock - 1; // nastavení reload hodnoty (to je ta od které se dekrementuje až k nule a potom je znovu naètena)
// pokud to správnì chápu, tak SystemCoreClock je jedna vteøina (odpovídá 1600000(2 na 24))
SysTick->CTRL |= SysTick_CTRL_CLKSOURCE_Msk; // nastavení bitu ENABLE v registru Control na hodnotu jedna (enabled))
SysTick->CTRL |= SysTick_CTRL_ENABLE_Msk; // nastavení bitu CLKSOURCE v registru Control na hodnotu jedna (procesor clock (AHB))

GPIOConfigurePin(RGBLED_BLUE,ioPortOutputPushPull);

  /* Infinite loop */
while (1)
{
   GPIOToggle(RGBLED_BLUE);
   while(!(SysTick->CTRL & SysTick_CTRL_COUNTFLAG_Msk)) // count flag bit v registru CTRL nastaví jednièku jeli hodnota èítaèe na nule (než se reloadne nová hodnota)..(pozor na to, je na bitu 16)
   {

   }


}

}
