/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2019-02-27

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/


#include "mina_shield_mbed.h"

volatile uint32_t ticks = 0; // promìná která symbolizuje dobìhnutí hodin
// "volatile" znamená že kompilátor tuto promìnou nebude optimalizovat, to je tøeba, protože by jinak mohl kompilátor dojít k chybným závìrùm o fknci nìkterých programových konstrukcí a nesprávnì program optimalizovat

void SysTick_Handler(void) // TODO funkce musí mít pøesnì takovýto název, jinak se pøi pøerušení volá defalutnì nastavená
{
	ticks++;
}

int main(void)
{

	// PWM: ARR jsou výška schodù, CCRx je kdy se pulz v dané periodì "vypne", pokud je CCRx v pulce schodù, dává 50%, pokud víc, støídá bude vìtší

	uint32_t timeConstant = 100;

	SystemCoreClockUpdate();

	SysTick_Config(SystemCoreClock / 1000);

	uint32_t apb2 = SystemCoreClock; //TODO dopln podle RCC (16MHz)

	if (!(RCC->APB2ENR & RCC_APB2ENR_TIM1EN)) // v DataSheet str15 je vidìt že TIM1 je na sbìrnici APB2
	{
			RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;
			RCC->APB2RSTR |= RCC_APB2RSTR_TIM1RST;
			RCC->APB2RSTR &= ~RCC_APB2RSTR_TIM1RST;
	} // nastaven TIM1

		TIM1->CR1 = 0 | TIM_CR1_ARPE; // up counter(poèítá nahoru)
		TIM1->CR2 = 0;
		TIM1->PSC = apb2 / 1E6 - 1; // (1us) => MHz
		TIM1->ARR = 128-1; // (1000-1 => pøeteèe každou 1ms => kHz)
		TIM1->CR1 = TIM_CR1_CEN;

		TIM1->BDTR |= TIM_BDTR_MOE; //nutno nastavit, na jedna (povoluje OC výstupù), urèeno k jednoduchému odpojení motorových budièù

		GPIOConfigurePin(RGBLED_BLUE, ioPortAlternatrPushPull);
		GPIOConfigureAlternativFunction(RGBLED_BLUE, 1); // AF01 odpovida TIM1_CH2N => datasheet


		TIM1->CCMR1 &= ~TIM_CCMR1_OC2M; // Pozor!! nutno OC2M protože potøebueme druhý kanál!!!!
		TIM1->CCMR1 |= TIM_CCMR1_OC2M_2 | TIM_CCMR1_OC2M_1; // _2 a _1 jako prvni a druhy bit, 110 – PWM 1
		TIM1->CCER |= TIM_CCER_CC2E; // kánál 2 enable (musí být jenom E!!!)
		TIM1->CCR2 = TIM1->ARR / 2; // polovina TIM3 ARR, takže støída 50%

	    // RM str 355

		if (!(RCC->APB1ENR & RCC_APB1ENR_TIM3EN)) // v DataSheet str15 je vidìt že TIM1 je na sbìrnici APB2
		{
				RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
				RCC->APB1RSTR |= RCC_APB1RSTR_TIM3RST;
				RCC->APB1RSTR &= ~RCC_APB1RSTR_TIM3RST;
		} // nastaven TIM3

			TIM3->CR1 = 0 | TIM_CR1_ARPE; // up counter(poèítá nahoru)
			TIM3->CR2 = 0;
			TIM3->PSC = apb2 / 1E6 - 1; // (1us) => MHz
			TIM3->ARR = 128-1; // (pøeteèe každou 256us)
			TIM3->CR1 = TIM_CR1_CEN;

			GPIOConfigurePin(RGBLED_RED, ioPortAlternatrPushPull);
			GPIOConfigureAlternativFunction(RGBLED_RED, 2); // AF02 odpovida TIM3_CH1N => datasheet


			TIM3->CCMR1 &= ~TIM_CCMR1_OC1M; // Pozor!! nutno OC1M protože potøebueme první kanál!!!!
			TIM3->CCMR1 |= TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1; // _2 a _1 jako prvni a druhy bit, 110 – PWM 1
			TIM3->CCER |= TIM_CCER_CC1E; // kánál 1 enable (musí být jenom E!!!)
			TIM3->CCR1 =  TIM3->ARR / 2; // polovina TIM3 ARR, takže støída 50%

			GPIOConfigurePin(RGBLED_GREEN, ioPortAlternatrPushPull);
			GPIOConfigureAlternativFunction(RGBLED_GREEN, 2); // AF02 odpovida TIM3_CH2N => datasheet


			TIM3->CCMR1 &= ~TIM_CCMR1_OC2M; // Pozor!! nutno OC2M protože potøebueme druhý kanál!!!!
			TIM3->CCMR1 |= TIM_CCMR1_OC2M_2 | TIM_CCMR1_OC2M_1; // _2 a _1 jako prvni a druhy bit, 110 – PWM 1
			TIM3->CCER |= TIM_CCER_CC2E; // kánál 1 enable (musí být jenom E!!!)
			TIM3->CCR2 = TIM3->ARR / 2; // polovina TIM3 ARR, takže støída 50%

		    // RM str 355

			uint8_t b = 0;


			while (1) {

				if (ticks >= timeConstant) {
							timeConstant = ticks + 50;

					        b+=4;

					        TIM3->CCR1 = b;
							TIM3->CCR2 = b;
							TIM1->CCR2 = b;

							if(b>=127)
							{
							b = 0;
							}

					}

		}
	}
