/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2019-03-15

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm_core.h"
#include "mpp_shield.h"
#include "system_stm32f4xx.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/

	int main(void)
	{

	GPIOConfigurePin(RGBLED_BLUE,ioPortOutputPushPull);

	if (!(RCC->APB1ENR & RCC_APB1ENR_TIM3EN))
	{
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
	RCC->APB1RSTR |= RCC_APB1RSTR_TIM3RST;
	RCC->APB1RSTR &= ~RCC_APB1RSTR_TIM3RST;
	}

	TIM3->CR1 = TIM_CR1_DIR; // DIR = 1 = dekrementace
	TIM3->CR2 = 0; //prostì jen reset
	TIM3->PSC = SystemCoreClock / 1000 - 1; //pøeddìliè, to bylo jako když jsme nastavali systick, prostì jen nastavujeme že jeden dobìh se bude rovnat jedné milisekundì (aspoò kurva doufám)
	TIM3->ARR = 999; // (1000 - 1) - tj. 1Hz, 1000ms (jedna sekunda)
	TIM3->CR1 |= TIM_CR1_CEN; // enable


	while (1)
	{

		if (TIM3->SR & TIM_SR_UIF) // nenula = nastaven bit (pokud je v registru SR na bitì UIF(signalizace pøeteèení) nula, signalizuje to že došlo k pøeteèení)
		{
		TIM3->SR &= ~TIM_SR_UIF; // nastavíme bit který signalizuje pøeteèení zpìt do jednièky abychom mohli detekovat i pøíštì
		GPIOToggle(RGBLED_BLUE);
		}
	}
}
