/*
 ******************************************************************************
 File:     main.c
 Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2019-03-06

 The MIT License (MIT)
 Copyright (c) 2019 STMicroelectronics

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 ******************************************************************************
 */

/* Includes */
#include "mpp_shield.h"
#include "system_stm32f4xx.h"
#include "nucleo_usart.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */


   volatile bool onBuzz = false;

   void TIM3_IRQHandler(void) // obsluha preruseni od TIM3
   {
    TIM3->SR &= ~TIM_SR_UIF; // shodit priznak !!
    if(onBuzz)
    {
    GPIOToggle(BUZZER); // pipak
    }
   }



char buffer[100];

int bufferSize = 0;

int main(void) {

	GPIOConfigurePin(BUZZER,ioPortOutputPushPull);
	GPIOConfigurePin(BUTTON_LEFT,ioPortInputFloat);

	if (!(RCC->APB1ENR & RCC_APB1ENR_TIM3EN))
	{
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
	RCC->APB1RSTR |= RCC_APB1RSTR_TIM3RST;
	RCC->APB1RSTR &= ~RCC_APB1RSTR_TIM3RST;
	}

	TIM3->DIER = TIM_DIER_UIE; // nastaveni preruseni
	NVIC_EnableIRQ(TIM3_IRQn); // nastaveni preruseni

	TIM3->CR1 = TIM_CR1_DIR; // DIR = 1 = dekrementace
	TIM3->CR2 = 0; //prostì jen reset
	TIM3->PSC = SystemCoreClock/1000000-1 ; //
	TIM3->ARR = 1000-1; // jedna milisekunda
	TIM3->CR1 |= TIM_CR1_CEN; // enable

	Usart2Initialization(38400);	

    puts("\nStart App\n");

	while (1) {

		if(!GPIORead(BUTTON_LEFT))
				{

					if(!onBuzz)
					{
						onBuzz = true;
					}
					else
					{
						onBuzz = false;
					}

				    while(!GPIORead(BUTTON_LEFT))
					{

					}
				}

		if (IsUsart2Recived()) { // funkci musím volat až když vím že tam nìjaký data èekají, jinak by tam èekal dokud nepøijou a program by se zastavil proto testovací funkce, kdybych dal if testovani do funkce pro cteni, nepoznal bych kdy prisla nula a kdy mi to vratilo nulu jako že podminka nebyla splnena

			char x = Usart2Recived();

			if(x == 'e')
			{
				uint32_t frequency = 0;

				printf("Zadana frekvence: ");
				for(int i = 0; i < bufferSize ; i++)
				{

					printf("%c",buffer[i]);


					uint pretypovani = ((uint)(buffer[i])-48);

					frequency = 10*frequency + pretypovani;

					buffer[i] = '0';
				}

				float time =((1/((float)frequency))*1000000); // frekvenci zadávám v Hz

				TIM3->ARR = time-1; // tady cci cas v us

				bufferSize = 0;
				printf("\n");
			}
			else
			{
				buffer[bufferSize] = x;
				bufferSize++;
			}
		}



	}
}
