/*
 ******************************************************************************
 File:     main.c
 Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2019-03-06

 The MIT License (MIT)
 Copyright (c) 2019 STMicroelectronics

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 ******************************************************************************
 */

/* Includes */
#include "mina_shield_mbed.h"
#include "system_stm32f4xx.h"
#include "nucleo_usart.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

volatile bool tickElapsed = false; // promìná která symbolizuje dobìhnutí hodin
// "volatile" znamená že kompilátor tuto promìnou nebude optimalizovat, to je tøeba, protože by jinak mohl kompilátor dojít k chybným závìrùm o fknci nìkterých programových konstrukcí a nesprávnì program optimalizovat

void SysTick_Handler(void) // tato funkce musí mít pøesnì takovýto název, jinak se pøi pøerušení volá defalutnì nastavená
{
tickElapsed = true;
}

int main(void) {

	SystemCoreClockUpdate();

	SysTick_Config(SystemCoreClock); // nastavení èasovaèe pro pøerušení

	  GPIOConfigurePin(POT_LEFT,ioPortAnalog);
	  GPIOConfigurePin(POT_RIGHT,ioPortAnalog);

	  Usart2Initialization(38400);

	  if (!(RCC->APB2ENR & RCC_APB2ENR_ADC1EN))
	  {
	  RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;
	  RCC->APB2RSTR |= RCC_APB2RSTR_ADCRST; // ADCRST je reset bit pro všechny ADC
	  RCC->APB2RSTR &= ~RCC_APB2RSTR_ADCRST; //
	  }

	  ADC1->CR1 = 0 | ADC_CR1_SCAN; // povolení práce s SQR kanály
	  // RES defalutnì nastaven na 00 (12 bitù), takže do toho se nemontuju
	  ADC1->CR2 = 0; // ALIGN = 0 (zarovnání vpravo)
	  // ADON (zapnutí provedeme až uplnì nakonec)
	  ADC1->SMPR1 = 0; // urèení doby pøevodu, chceme pouze pro kanál 0 takže SMPR2
	  ADC1->SMPR2 = ADC_SMPR2_SMP0_1; // 010, pro kanál nula = 28 cyklu


	  ADC1->SQR1 = 0; // L = 0000 = 1 konverze
	  ADC1->SQR2 = 0;
	  ADC1->SQR3 = 0; // SQ1 = 00000 = AD kanal 0
	  ADC->CCR = 0; // TSVREFE = 0 (neni teplotní sensor, neni interní reference), ADCPRE = 0 (APB2 / 2)
	  // CCR spoleèný pro všechny, proto nemá èíslo
	  ADC1->CR2 |= ADC_CR2_ADON; // zapnuti AD

	  uint16_t w = 0;

	while (1) {

		if (tickElapsed)
		{
		tickElapsed = false;

		for(int i = 0;i<2;i++){

		  ADC1->SQR3 = (!i)?0:1; // zmìna kanálu na AD0 = PA0, AD1 = PA1

		  ADC1->CR2 |= ADC_CR2_SWSTART; // spusteni prevodu

		  while(!(ADC1->SR & ADC_SR_EOC));

		  w = ADC1->DR;

		printf((!i)?"POT LEFT: %d      ":"POT RIGHT: %d\n",w);
		}


     	}


}

}
