/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2019-02-22

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
  int i = 0;

  /**
  *  IMPORTANT NOTE!
  *  The symbol VECT_TAB_SRAM needs to be defined when building the project
  *  if code has been located to RAM and interrupts are used. 
  *  Otherwise the interrupt table located in flash will be used.
  *  See also the <system_*.c> file and how the SystemInit() function updates 
  *  SCB->VTOR register.  
  *  E.g.  SCB->VTOR = 0x20000000;  
  */

  /* My note */
  // RCC je blok periferních registrù (ukazatel na strukturu, takže pøístušné registry jsou pøístupné pøes šipku(nepøímý pøístup))
  // operátor -> nepøímý pøístup ke èlenu struktury (teèka . je pøímý pøístup) ale tady máme UKAZATEL, takže potøebujeme pøístup nepøímý!
  // AHB1ENR(nebo AHB1RSTR) jsou registry v bloku periferních registrù RCC
  // "RCC_AHB1ENR_GPIOAEN" atd.. jsou konkterni konstanty reprezentujici pozici bitu v registru (napø kdyby to byl pátý bit v 16ti bitovém registru tak konstanta vypadá takhle: 0000 0000 0010 0000), registry jsou buï 16ti nebo 32 bitové

  /* My code */
  if(!(RCC ->AHB1ENR |= RCC_AHB1ENR_GPIOAEN)) // pokud nejsou povoleny hodiny (povolení hodin celé bránì PA)
  {
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN; // zapni hodiny pro periferii GPIO (Nastavuji bit(který má uloženou hodnotu pod konstanou "RCC_AHB1ENR_GPIOAEN") v registru AHB1ENR do jedièky(or jednièka na tom bitu))
    RCC->AHB1RSTR |= RCC_AHB1RSTR_GPIOARST; // proveï restart periferie GPIO (teï ovládáme registr AHB1RSTR, nastavime bit "RCC_AHB1RSTR_GPIOARST" do jednicky a o radek niz do nuly aby se resetovala periferie)
    RCC->AHB1RSTR &= ~RCC_AHB1RSTR_GPIOARST; // konec restartu periferie GPIO (zpìt do nuly(negaci bitu "RCC_AHB1RSTR_GPIOARST" (to ale ovsem znamená že na všech ostatnich mistech krom na tomhle bitu je nyní jednièka) andujeme s pùvodním registrem(všude jsou jednièky, tam se hodnota nemeni, jen tak kde je nula bude bit nastaven do nuly) ))

  }

  GPIOA->MODER |= 0x01<<(5*2); // takže MODER je registr periferie GPIOA (vstupnì výstupní porty pro všeobecné úèely, na konci A až F, jen jako poøadí, jsou stejné snad), nastavuji dvìmi bity, takže pokud máme 16 portù (který umìjí být vstupy i výstupy), tak potøebujeme 32 bitový registr.. takže my potøebujeme nastavit port 5 (ten je pøipojen na LED) (pozor, èíslují se od nuly!!!) to znamená že 5 krát 2 (vstup/vystup) to je deset, takže 10krát potøebujeme posunout jednièku aby na registru vznikla kombinace 01(00 - vstup, 10 - alternativní funkce, 11 - analog mode) na registru v místì 10,11(to je pátý port)
  GPIOA->OTYPER &= ~(1<<5); // registr "OTYPER" je registr který urèuje typ výstupu (výstup mùže být buï: 1 - open drain (použit pouze tranzistor do zemì, pokud není výstup v jednièce, tak je v nule) nebo 0 - push pull (oba tranzistory na výstupu jsou použity, pokud neni výstup v jednièce tak je ve stavu vysoké impedance Z)), my chceme typ push pull takže jdeme nastavit nulu a na pozici v registru 5 (u tohoto portu chceme nastavit push pull)
  GPIOA->OSPEEDR |= 0x03<<(5*2); //registr OSPEEDR øídí rychlost, zase jsou to dva bity na jeden výstup jako u MODER, ale tady chci nastavit hodnotu 11(higt)(00 - low, 01 - medium, 10 - fast)  proto posunuji ne jednièku ale trojku o 5 krát 2 bity doleva

  // zkusil jsem si zapojit externi LEDku, pozor na to že ve schématu je port 6 (PA6) vyznaèen pod portem PA5, nikoliv nad jak bych asi èekal
  /*
  GPIOA->MODER |= 0x01<<(6*2);
  GPIOA->OTYPER &= ~(1<<6);
  GPIOA->OSPEEDR |= 0x03<<(6*2);
  */

  /* Infinite loop */

  while (1)
  {
   // GPIOA -> ODR ^= 1<<6;
   GPIOA -> ODR ^= 1<<5; // "ODR" je registr výstupní hodnoty (output data register), my chceme aby se hodnota na vystupu menila, tudiz logická operace XOR ^ a zase o 5 bitù posunutá, protože chceme port 5
   for(i = 0;i<500000;i++); // cekaci cyklus
  }
}

